services:
  blinkbridge:
    # docker buildx build --platform=linux/amd64,linux/arm64 -t phntom/blinkbridge:0.0.1 --push .
    image: phntom/blinkbridge:0.0.1
    volumes:
      - ./config:/config
      # path for temporary files (video clips, concat files, etc.)
      - /tmp/blinkbridge:/working
      # use below instead to use RAM instead of disk for temporary files
      # - type: tmpfs
      #   target: /working
      #   tmpfs:
      #     size: 52428800  # 50MB  
    tty: true # for color logs
    environment:
      - BLINKBRIDGE_CONFIG=/config/config.json
    ports:
      - 8558:8000
  mediamtx:
    image: bluenviron/mediamtx
    container_name: mediamtx
    ports:
      - 8554:8554